package me.mint.tntfusetimer.config;

import me.mint.tntfusetimer.TNTFuseTimer;
import net.minecraft.client.gui.GuiScreen;
import net.minecraftforge.common.config.ConfigElement;
import net.minecraftforge.fml.client.config.GuiConfig;
import net.minecraftforge.fml.client.config.IConfigElement;

import java.util.ArrayList;
import java.util.List;

/**
 * The settings screen, generated by Forge from the config categories.
 */
public class ModGuiConfig extends GuiConfig {

    public ModGuiConfig(GuiScreen parent) {
        super(parent, collectElements(), TNTFuseTimer.MODID, false, false, "TNT Fuse Timer");
    }

    @SuppressWarnings({"unchecked", "rawtypes"})
    private static List<IConfigElement> collectElements() {
        List<IConfigElement> elements = new ArrayList<IConfigElement>();
        elements.addAll(new ConfigElement(
                ModConfig.getConfig().getCategory(ModConfig.CATEGORY_GENERAL)).getChildElements());
        elements.addAll(new ConfigElement(
                ModConfig.getConfig().getCategory(ModConfig.CATEGORY_DISPLAY)).getChildElements());
        elements.addAll(new ConfigElement(
                ModConfig.getConfig().getCategory(ModConfig.CATEGORY_BEDWARS)).getChildElements());
        return elements;
    }
}
